views:
  logo:
    size_image: "80x50"
    url: "images.jpg"
subjects:
  per_page: 5
  min_date_duration: 1
  num_of_created_tasks: 5
  is_present: true
  min_c: 2
  max_c: 255
  users:
    per_page: 10
courses:
  per_page: 5
  is_present: true
  min_c: 2
  max_c: 255
date_format: "%d/%m/%Y"
